import time
moveLinear("AutoSort", 1)
openGripper()
moveLinear("AutoSort", 2)
closeGripper()
time.sleep(2.5)
print getJawMilimeters()
time.sleep(1)
openGripper()
moveLinear("AutoSort", 3)
time.sleep(1)
moveLinear("AutoSort", 4)
time.sleep(1)
moveLinear("AutoSort", 5)
closeGripper()
time.sleep(2.5)
print getJawMilimeters()
time.sleep(1)
moveLinear("AutoSort", 6)
time.sleep(1)
moveLinear("AutoSort", 7)
time.sleep(2)
moveLinear("AutoSort", 8)
time.sleep(2.5)
openGripper()
time.sleep(2.5)
print getWeight()
time.sleep(1)
moveLinear("AutoSort", 9)
time.sleep(1)
moveLinear("AutoSort", 10)
time.sleep(1)
moveLinear("AutoSort", 11)
time.sleep(1)
closeGripper()
time.sleep(2.5)
print getJawMilimeters()
time.sleep(1)
moveLinear("AutoSort", 12)

