--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 06 2012 12:52
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO
--
-- Drop Table    : 'Software'   
--
DROP TABLE Software
GO
--
-- Drop Table    : 'Components'   
--
DROP TABLE Components
GO
--
-- Drop Table    : 'Users'   
--
DROP TABLE Users
GO
--
-- Drop Table    : 'Producers'   
--
DROP TABLE Producers
GO
--
-- Drop Table    : 'Permissions'   
--
DROP TABLE Permissions
GO
