--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 06 2012 12:52
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'F12I4PRJ4Gr3'
--
USE F12I4PRJ4Gr3
GO

--
-- Create Table    : 'Permissions'   
-- ID              :  
-- Name            :  
--
CREATE TABLE Permissions (
    ID             INT NOT NULL UNIQUE,
    Name           VARCHAR NOT NULL,
CONSTRAINT pk_Permissions PRIMARY KEY CLUSTERED (ID))
GO

--
-- Create Table    : 'Producers'   
-- ID              :  
-- Name            :  
-- Description     :  
--
CREATE TABLE Producers (
    ID             INT NOT NULL UNIQUE,
    Name           VARCHAR NOT NULL,
    Description    VARCHAR NOT NULL,
CONSTRAINT pk_Producers PRIMARY KEY CLUSTERED (ID))
GO

--
-- Create Table    : 'Users'   
-- ID              :  
-- Name            :  
-- Description     :  
-- Permission      :  (references Permissions.ID)
--
CREATE TABLE Users (
    ID             INT NOT NULL UNIQUE,
    Name           VARCHAR NOT NULL,
    Description    VARCHAR NOT NULL,
    Permission     INT NULL,
CONSTRAINT pk_Users PRIMARY KEY CLUSTERED (ID),
CONSTRAINT fk_Users FOREIGN KEY (Permission)
    REFERENCES Permissions (ID)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Components'   
-- ID              :  
-- Name            :  
-- Description     :  
-- Producer        :  (references Producers.ID)
--
CREATE TABLE Components (
    ID             INT NOT NULL UNIQUE,
    Name           VARCHAR NOT NULL,
    Description    VARCHAR NOT NULL,
    Producer       INT NULL,
CONSTRAINT pk_Components PRIMARY KEY CLUSTERED (ID),
CONSTRAINT fk_Components FOREIGN KEY (Producer)
    REFERENCES Producers (ID)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Software'   
-- ID              :  
-- Name            :  
-- Description     :  
-- Producer        :  (references Producers.ID)
--
CREATE TABLE Software (
    ID             INT NOT NULL UNIQUE,
    Name           VARCHAR NOT NULL,
    Description    VARCHAR NOT NULL,
    Producer       INT NULL,
CONSTRAINT pk_Software PRIMARY KEY CLUSTERED (ID),
CONSTRAINT fk_Software FOREIGN KEY (Producer)
    REFERENCES Producers (ID)
    ON UPDATE CASCADE)
GO

